version: "3.1"

services:
  database:
    image: postgis/postgis:15-3.3-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"

  server:
    build: ./server
    restart: always
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: database
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      - database
    ports:
      - "8080:8080"
